apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      containers:
      - name: httpd-app
        image: httpd
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: httpd-cm
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: httpd-app
  ports:
  - port: 9201
    targetPort: 80
    nodePort: 31000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-cm
  labels:
    app: httpd-app
    component: httpd
data:
  dbname: mysql
  log_level: debug
  custom_data:
    image.public.key=1234
    rs.public.key=aspe
